services:
  - type: web
    name: viddy-2-0
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app